services:
  - type: web
    name: ayanfe-ai
    env: node
    plan: starter
    buildCommand: |
      npm install --include=dev
      npm install @vitejs/plugin-react --save-dev
      npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: ayanfe-db
          property: connectionString

databases:
  - name: ayanfe-db
    plan: free
    postgresMajorVersion: 15
    ipAllowList: []
